version: '3.1'
services:
  memcached:
    image: 'memcached:alpine'

  webserver:
    image: 'nginx:alpine'
    working_dir: /app
    env_file:
      - .env
    volumes:
      - '.:/app'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '62000:80'

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /app
    volumes:
      - '.:/app'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'